### ISSUE TITLE
Did a git clone and there is nothing in /opt/OpenModScan

### ISSUE THREAD

**Issue by mitchell-pioneer** [sanny32/OpenModScan#10]
Im looking for the install script that should be in /opt/OpenModScan

Any help would get appreciated.

**Comment by sanny32** [comment]
Hello @mitchell-pioneer. In /opt/OpenModScan there is no install script, only run program script. Do you need this script?

**Comment by mitchell-pioneer** [comment]
yes please.

**Comment by sanny32** [comment]
[omodscan.gz](https://github.com/user-attachments/files/15922894/omodscan.gz)
