### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Mrjie-xiansheng** [sanny32/OpenModScan#12]
![image](https://github.com/user-attachments/assets/d4e1e507-c624-46d8-9b5e-e965bbff23e3)
![Uploading 1.png…]()

**Comment by sanny32** [comment]
Sorry, i don’t understand Chinese language.

**Comment by Ekristoffe** [comment]
The error message is about a printer connection:
![IMG_1895](https://github.com/user-attachments/assets/cacf907b-ff15-41d8-b5df-0b6fb84352dd)

I have no idea if this is relevant…
Maybe can be close as non relevant …

**Comment by sanny32** [comment]
There is a Qt dialog, not OpenModscan. @Mrjie-xiansheng you must reconfigure your OS Windows to avoid this dialog.
