### ISSUE TITLE
Support for Modbus RTU

### ISSUE THREAD

**Issue by yashsonyyy** [sanny32/OpenModScan#14]
Hi Sanny32,
Thanks for such a useful tool. I could see you fetch most of the data and display everything which makes debugging easy.
I request if you can add the support for modbus RTU too?
It would be okay if you help around this too.
Thanks,
Yash Soni

**Comment by sanny32** [comment]
Hi @yashsonyyy.
Modbus RTU protocol is supported by OpenModscan.
