### ISSUE TITLE
Possibility of macOS version

### ISSUE THREAD

**Issue by patkepa** [sanny32/OpenModScan#16]
Hello, is there possibility of porting OpenModScan for macOS? Do you think there are any blockers towards that? If there's nothing serious stopping against compiling it against macOS I would be willing to attempt it and contribute to the project, just would like to ask in advance 😃 

Thanks!

**Comment by sanny32** [comment]
Hello @patkepa. I have no macOS to build and test program, but I think that there is no blockers to do that. You can build and test program for macOS. I don't mind.

**Comment by patkepa** [comment]
Thanks for quick reply. 
I managed to build it on MacOS and it seems to work fine, with few slight aesthetic bugs.
Thanks for the good work 😃
