### ISSUE TITLE
Offset +1 on all registers

### ISSUE THREAD

**Issue by MarkoBursic** [sanny32/OpenModScan#2]
If I read holding register  Address 0001 it actually tries to read register 0, so exception is throwed. To read register 1 you have to set Address to  0002. It applies to all kind of registers.

![image](https://github.com/sanny32/OpenModScan/assets/7830293/186b5509-32d8-4609-a4eb-e3ba3e0c74ab)

![image](https://github.com/sanny32/OpenModScan/assets/7830293/49c6cb97-5930-4166-ae3e-29fee7294cf4)

**Comment by sanny32** [comment]
Please let me know from what register 0 or 1 address space started in your device.

**Comment by MarkoBursic** [comment]
After examination of the device (Corrigo HVAC controller) and reading the Modbus protocol specs I came to conclusion that maybe the device protocol is implemented in incorrect way. For example, from manual the outdoor temperature is input register 1, translated in modbus space this shall be input register 30001, then subtract 30001 as per modbus specs, the query address shall be 0000 (blue numbers in Wireshark debug), but it throws error, this for any range of registers (coils, contacts, input registers, holding registers).

Short: Closed, Modbus device incorrectly implemented.
