### ISSUE TITLE
Feature Request: Write multiple registers

### ISSUE THREAD

**Issue by bobemoe** [sanny32/OpenModScan#23]
First, fantastic app, many thanks :)

I often find myself writing multiple holding regs. I have to double click the value, click the input box, enter value, repeat for next one. It works but is a bit cumbersome. 

Would it be possible to have a way to select multiple registers for bulk update?

**Comment by sanny32** [comment]
Hello @bobemoe. You can preset regs via menu Setup->Extended->Preset Regs
![image](https://github.com/user-attachments/assets/668fcf58-6094-4c44-b1e2-9811cf98d660)

And then input register values with form
![image](https://github.com/user-attachments/assets/773175de-1259-42f8-b31c-0a643a7a1662)

**Comment by bobemoe** [comment]
Ah yes, sorry I'd missed that, it appears to be exactly what I was looking for :)
