### ISSUE TITLE
Address scan

### ISSUE THREAD

**Issue by ortegahernandes** [sanny32/OpenModScan#25]
In setup / extended / address scan 

In timeout events, it is not proceeding to the next address, it is stuck at the same address until it responds.

**Comment by sanny32** [comment]
This looks like the scan is stopped, but in reality the scan is not stopped, but slowed down significantly due to the response timeout and the number of read retries, which are set here

![image](https://github.com/user-attachments/assets/2705c4b9-7be6-4eef-8cbd-ec0cbe1da6a1)

**Comment by ortegahernandes** [comment]
You're right, the timeout was long and the number of attempts was too.
