### ISSUE TITLE
There is no 32 bit Signed/Unsigned register with swap option (like there is for Float register)

### ISSUE THREAD

**Issue by guy22israel** [sanny32/OpenModScan#5]
Hello,

There are many RTUs supporting 32bit registers (signed/unsigned32). It would be nice if the tool can support this as well so it will have all most widely used options:
- Bits
- Bytes (optional)
- 16bit Signed/unsigned register (input/holding) + bytes swap
- 32bit Signed/unsigned register (input/holding) + words/bytes swap
- 32bit Float register (input/holding) + words/bytes swap
- 64bit Float register (input/holding) - less common

Thank you,
Omer.

**Comment by sanny32** [comment]
Fixed at version [1.5.0](https://github.com/sanny32/OpenModScan/releases/tag/1.5.0)
