### ISSUE TITLE
Is possible to read and write 64bit register

### ISSUE THREAD

**Issue by brunosso** [sanny32/OpenModScan#8]
Hi!

thanks for this tool!

Is possibile to read/write 64bit register.
I need to access to eneergy meter data stored in INT64 type

Do you think is possible?

**Comment by sanny32** [comment]
Hello. 
There is no 64-bit integer support now. But it is possible to implement feature in future release. Do you need this feature?

**Comment by brunosso** [comment]
Thanks for the immediate reply....

I needed for reset the partial energy readings of this energy gateway [https://www.se.com/it/it/product/PAS600/ecostruxure-panel-server-universal-concentratore-wireless-e-gateway-modbus-110277-vac-dc/](url)
You can download the modbus address list in the file DOCA0241EN-08.zip

Thanks

**Comment by sanny32** [comment]
Implemented at version 1.7.0
